### ISSUE TITLE
bead save error message

### ISSUE THREAD

**Issue by bszilagyi** [e3krisztian/bead#44]
sys_argv = ['/usr/bin/bead', 'save', 'latest_de']
Traceback (most recent call last):
  File "/usr/bin/bead/bead_cli/main.py", line 158, in main
    retval = run(config_dir, sys.argv[1:])
  File "/usr/bin/bead/bead_cli/main.py", line 135, in run
    return parser.dispatch(argv)
  File "/usr/bin/bead/bead_cli/cmdparse.py", line 208, in dispatch
    return run(args) or 0
  File "/usr/bin/bead/bead_cli/workspace.py", line 110, in run
    location = box.store(workspace, timestamp())
  File "/usr/bin/bead/bead/box.py", line 169, in store
    workspace.pack(zipfilename, freeze_time=freeze_time, comment=ARCHIVE_COMMENT)
  File "/usr/bin/bead/bead/workspace.py", line 117, in pack
    _ZipCreator().create(zipfilename, self, freeze_time, comment)
  File "/usr/bin/bead/bead/workspace.py", line 280, in create
    with zipfile.ZipFile(
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/srv/bead-box/latest/dropbox_encrypted/firmname_search_on_complex_names_20200508_20201211T152956094686+0100.zip'

Python:
------
3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]

Bead source:
-----------
origin:  git@github.com:e3krisztian/bead.git
branch:  master
date:    2020-10-23T16:23:28+02:00
hash:    1805272
version: v0.8.1

**Comment by e3krisztian** [comment]
Sorry for late reply, I have email notifications turned off, and rarely visit my repos.

I am curious what happened - my guess is, that the directory to save to was no longer existing.
@bszilagyi do you remember what was the problem?

**Comment by e3krisztian** [comment]
I have successfully recreated the problem.
Indeed it happens, when the box directory is no longer available.

**Comment by bszilagyi** [comment]
I am sorry to not reply. Yes, that was exactly the problem. It was on the
new server, and Olivér was still organizing the directory structure.
The issue was solved quickly. I have just slavishly followed the kind
suggestion in the error message to open an issue, but later I forgot to
close it. I am sorry again.
It was very kind of you to look into the issue.



Krisztián Fekete ***@***.***> ezt írta (időpont: 2021. márc.
22., H, 22:43):

**Comment by e3krisztian** [comment]
@bszilagyi Thank you for making this issue.

It is a genuine error! Ideally, you should never see such a message.

It will be fixed.

----

If you have any such problem you could work around easily, please report
the issue as well as the workaround.

Bead should *just work*, without workarounds.

Please continue reporting problems! :)

**Comment by bszilagyi** [comment]
In this case a more explicit error message would do. Something like: "The bead box directory does not seem to exist."
