### ISSUE TITLE
Permission error with `input update`

### ISSUE THREAD

**Issue by korenmiklos** [e3krisztian/bead#47]
```
sys_argv = ['/usr/bin/bead', 'input', 'update', 'owner-country']
Traceback (most recent call last):
  File "/usr/bin/bead/bead_cli/main.py", line 158, in main
    retval = run(config_dir, sys.argv[1:])
  File "/usr/bin/bead/bead_cli/main.py", line 135, in run
    return parser.dispatch(argv)
  File "/usr/bin/bead/bead_cli/cmdparse.py", line 208, in dispatch
    return run(args) or 0
  File "/usr/bin/bead/bead_cli/input.py", line 140, in run
    self.update_one_input(args)
  File "/usr/bin/bead/bead_cli/input.py", line 203, in update_one_input
    _update_input(workspace, input, bead)
  File "/usr/bin/bead/bead_cli/input.py", line 218, in _update_input
    _check_load_with_feedback(workspace, input.name, bead)
  File "/usr/bin/bead/bead_cli/input.py", line 276, in _check_load_with_feedback
    workspace.unload(input_nick)
  File "/usr/bin/bead/bead/workspace.py", line 208, in unload
    fs.rmtree(input_dir / input_nick)
  File "/usr/bin/bead/bead/tech/fs.py", line 82, in rmtree
    make_writable(path)
  File "/usr/bin/bead/bead/tech/fs.py", line 68, in make_writable
    os.chmod(path, mode | stat.S_IWRITE)
PermissionError: [Errno 1] Operation not permitted: '/srv/sandbox/expat/almos/input/owner-country/owner-country-panel.dta'


Python:
------
3.8.10 (default, Nov 14 2022, 12:59:47)
[GCC 9.4.0]

Bead source:
-----------
origin:  git@github.com:e3krisztian/bead.git
branch:  master
date:    2020-10-23T16:23:28+02:00
hash:    1805272
version: v0.8.1
```

**Comment by e3krisztian** [comment]
It was caused by shared workspace/ restricting the permissions by ACLs.

I am afraid it is/was a server-environment problem, not something that can be reasonably handled within bead.
